version: '3'

services:  
   redis:
    image: "redis:alpine"
    command: redis-server 
    environment:
     - REDIS_REPLICATION_MODE=master
    ports:
     - "6379:6379"

   palaemon:
    image: endimion13/palaemon-registration:0.0.1c
    environment:
      NODE_ENV: "production"
      ENDPOINT: http://localhost:5040
      HTTPS_COOKIES: "false"
      REDIS: redis
      ISSUER_URL: https://dss1.aegean.gr/auth/realms/grnetEidas
      OIDC_REDIRECT_URI: http://localhost:5040/login/callback
      VC_REDIRECT_URI: http://localhost:5000/vc/response/kyb
      PORT: 5000
      DB_PROXY_URL: http://3851-2001-648-2000-cd-82fa-fe82-898-62eb.ngrok.io 
      # BASE_PATH: "issuer"
    ports:
      - 5040:5000

