import Head from 'next/head'
import React, { useState } from 'react';
import Layout from '../components/Layout'
import utilStyles from '../styles/utils.module.css';
import GridContainer from "../components/Grid/GridContainer";
import GridItem from "../components/Grid/GridItem";

import styles from "styles/jss/nextjs-material-kit/pages/landingPageSections/workStyle.js";
import {makeStyles} from "@material-ui/core/styles";

const useStyles = makeStyles(styles);

/*export async function getServerSideProps(context) {
    const res = await fetch('/query/searchGet?lei='+data.lei+'&legalName='+data.legalName);
    const data = await res.json()

    if (!data) {
        return {
            notFound: true,
        }
    }

    return {
        props: {data}, // will be passed to the page component as props
    }
}*/


export default function Home() {
    const classes = useStyles();
    const [lei, setLei] = useState('');
    const [legalName, setLegalName] = useState('');
    const [countryCode, setCountryCode] = useState('');
    const [kyb, setKyb] = useState('');
    const [errorMsg, setErrorMsg] = useState('');

    const handleSubmit = async e => {
        e.preventDefault();
        const data = {
            lei,
            legalName,
            countryCode,
        };

        if(lei === '' && (legalName === '' || countryCode === '')){
            setErrorMsg('Please provide either LEI or both Legal Name and Country Code');
            return;
        }
        setErrorMsg('')
        console.log(data);
        const response = await fetch('/query/searchGet?lei='+data.lei+'&legalName='+data.legalName+'&countryCode='+data.countryCode);
        const kybs = await response.json();
        if (kybs === "") {
            setKyb('');
        }
        setKyb(kybs);
        console.log(kyb);
    };

    return (
        <Layout home>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <form onSubmit={handleSubmit} >
                    <div>
                        <label htmlFor="lei">LEI:</label>
                        <input
                            id="lei"
                            type="text"
                            onChange={e => setLei(e.target.value)}
                        />
                        <label htmlFor="legalName">Legal Name:</label>
                        <input
                            id="legalName"
                            type="text"
                            onChange={e => setLegalName(e.target.value)}
                        />
                        <label htmlFor="countryCode">Country Code:</label>
                        <input
                            id="countryCode"
                            type="text"
                            onChange={e => setCountryCode(e.target.value)}
                        />
                    </div>
                    {errorMsg !== '' && <div>
                        {errorMsg}
                    </div>
                    }
                    <div>
                        <button type="submit">Send</button>
                    </div>
                </form>
                {/*{JSON.stringify(kybList)}*/}
                {kyb !== '' &&
                /*<table>
                    <tbody>
                    <tr>
                        <td>Legal Name</td>
                        <td>{kyb.legal_name}</td>
                    </tr>
                    <tr>
                        <td>Legal Person Identifier</td>
                        <td>{kyb.legal_person_identifier}</td>
                    </tr>
                    <tr>
                        <td>Jurisdiction Code</td>
                        <td>{kyb.jurisdiction_code}</td>
                    </tr>
                    <tr>
                        <td>Business Role</td>
                        <td>{kyb.business_role}</td>
                    </tr>
                    <tr>
                        <td>Address</td>
                        <td>{kyb.address}</td>
                    </tr>
                    <tr>
                        <td>LEI</td>
                        <td>{kyb.lei}</td>
                    </tr>
                    <tr>
                        <td>Vat Registration</td>
                        <td>{kyb.vat_registration}</td>
                    </tr>
                    <tr>
                        <td>Birthdate</td>
                        <td>{kyb.birthdate}</td>
                    </tr>
                    <tr>
                        <td>Trading Status</td>
                        <td>{kyb.trading_status}</td>
                    </tr>
                    <tr>
                        <td>Given Name</td>
                        <td>{kyb.given_name}</td>
                    </tr>
                    <tr>
                        <td>Family Name</td>
                        <td>{kyb.family_name}</td>
                    </tr>
                    <tr>
                        <td>Sub Jurisdiction</td>
                        <td>{kyb.sub_jurisdiction}</td>
                    </tr>
                    </tbody>

                </table>*/
                <div className={classes.section}>
                    <GridContainer justifyContent="center">
                        <GridItem cs={12} sm={12} md={8}>
                            <h2 className={classes.title}>Results</h2>

                            <GridContainer>
                                <GridItem xs={12} sm={12} md={6}>
                                    <div className={classes.textRight}>Legal Name</div>

                                </GridItem>
                                <GridItem xs={12} sm={12} md={6}>
                                    <div className={classes.textLeft}>{kyb.legal_name}</div>
                                </GridItem>
                                <hr className={classes.hrLine}></hr>
                                <GridItem xs={12} sm={12} md={6}>
                                    <div className={classes.textRight}>Legal Person Identifier</div>

                                </GridItem>
                                <GridItem xs={12} sm={12} md={6}>
                                    <div className={classes.textLeft}>{kyb.legal_person_identifier}</div>
                                </GridItem>
                                <hr className={classes.hrLine}></hr>
                                <GridItem xs={12} sm={12} md={6}>
                                    <div className={classes.textRight}>Jurisdiction Code</div>

                                </GridItem>
                                <GridItem xs={12} sm={12} md={6}>
                                    <div className={classes.textLeft}>{kyb.jurisdiction_code}</div>
                                </GridItem>
                                <hr className={classes.hrLine}></hr>
                                <GridItem xs={12} sm={12} md={6}>
                                    <div className={classes.textRight}>Business Role</div>

                                </GridItem>
                                <GridItem xs={12} sm={12} md={6}>
                                    <div className={classes.textLeft}>{kyb.business_role}</div>
                                </GridItem>
                                <hr className={classes.hrLine}></hr>
                                <GridItem xs={12} sm={12} md={6}>
                                    <div className={classes.textRight}>Address</div>

                                </GridItem>
                                <GridItem xs={12} sm={12} md={6}>
                                    <div className={classes.textLeft}>{kyb.address}</div>
                                </GridItem>
                                <hr className={classes.hrLine}></hr>
                                <GridItem xs={12} sm={12} md={6}>
                                    <div className={classes.textRight}>LEI</div>

                                </GridItem>
                                <GridItem xs={12} sm={12} md={6}>
                                    <div className={classes.textLeft}>{kyb.lei}</div>
                                </GridItem>
                                <hr className={classes.hrLine}></hr>
                                <GridItem xs={12} sm={12} md={6}>
                                    <div className={classes.textRight}>Vat Registration</div>

                                </GridItem>
                                <GridItem xs={12} sm={12} md={6}>
                                    <div className={classes.textLeft}>{kyb.vat_registration}</div>
                                </GridItem>
                                <hr className={classes.hrLine}></hr>
                                <GridItem xs={12} sm={12} md={6}>
                                    <div className={classes.textRight}>Birthdate</div>

                                </GridItem>
                                <GridItem xs={12} sm={12} md={6}>
                                    <div className={classes.textLeft}>{kyb.birthdate}</div>
                                </GridItem>
                                <hr className={classes.hrLine}></hr>
                                <GridItem xs={12} sm={12} md={6}>
                                    <div className={classes.textRight}>Trading Status</div>

                                </GridItem>
                                <GridItem xs={12} sm={12} md={6}>
                                    <div className={classes.textLeft}>{kyb.trading_status}</div>
                                </GridItem>
                                <hr className={classes.hrLine}></hr>
                                <GridItem xs={12} sm={12} md={6}>
                                    <div className={classes.textRight}>Given Name</div>

                                </GridItem>
                                <GridItem xs={12} sm={12} md={6}>
                                    <div className={classes.textLeft}>{kyb.given_name}</div>
                                </GridItem>
                                <hr className={classes.hrLine}></hr>
                                <GridItem xs={12} sm={12} md={6}>
                                    <div className={classes.textRight}>Family Name</div>

                                </GridItem>
                                <GridItem xs={12} sm={12} md={6}>
                                    <div className={classes.textLeft}>{kyb.family_name}</div>
                                </GridItem>
                                <hr className={classes.hrLine}></hr>
                                <GridItem xs={12} sm={12} md={6}>
                                    <div className={classes.textRight}>Sub Jurisdiction</div>

                                </GridItem>
                                <GridItem xs={12} sm={12} md={6}>
                                    <div className={classes.textLeft}>{kyb.sub_jurisdiction}</div>
                                </GridItem>


                            </GridContainer>

                        </GridItem>
                    </GridContainer>
                </div>
                }


            </main>
        </Layout>
    );
}