import Head from 'next/head'
import { useState } from 'react';
import Layout from '../components/layout'
import utilStyles from '../styles/utils.module.css';

/*export async function getServerSideProps(context) {
    const res = await fetch('/query/searchGet?lei='+data.lei+'&legalName='+data.legalName);
    const data = await res.json()

    if (!data) {
        return {
            notFound: true,
        }
    }

    return {
        props: {data}, // will be passed to the page component as props
    }
}*/


export default function Home() {
    const [lei, setLei] = useState('');
    const [legalName, setLegalName] = useState('');
    const [countryCode, setCountryCode] = useState('');
    const [kyb, setKyb] = useState('');
    const [errorMsg, setErrorMsg] = useState('');

    const handleSubmit = async e => {
        e.preventDefault();
        const data = {
            lei,
            legalName,
            countryCode,
        };

        if(lei === '' && (legalName === '' || countryCode === '')){
            setErrorMsg('Please provide either LEI or both Legal Name and Country Code');
            return;
        }
        setErrorMsg('')
        console.log(data);
        const response = await fetch('/query/searchGet?lei='+data.lei+'&legalName='+data.legalName+'&countryCode='+data.countryCode);
        const kybs = await response.json();
        if (kybs === "") {
            setKyb('');
        }
        setKyb(kybs);
        console.log(kyb);
    };

    return (
        <Layout home>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <form onSubmit={handleSubmit} >
                    <div>
                        <label htmlFor="lei">LEI:</label>
                        <input
                            id="lei"
                            type="text"
                            onChange={e => setLei(e.target.value)}
                        />
                        <label htmlFor="legalName">Legal Name:</label>
                        <input
                            id="legalName"
                            type="text"
                            onChange={e => setLegalName(e.target.value)}
                        />
                        <label htmlFor="countryCode">Country Code:</label>
                        <input
                            id="countryCode"
                            type="text"
                            onChange={e => setCountryCode(e.target.value)}
                        />
                    </div>
                    {errorMsg !== '' && <div>
                        {errorMsg}
                    </div>
                    }
                    <div>
                        <button type="submit">Send</button>
                    </div>
                </form>
                {/*{JSON.stringify(kybList)}*/}
                {kyb !== '' &&
                <table>
                    <tbody>
                    <tr>
                        <td>Legal Name</td>
                        <td>{kyb.legal_name}</td>
                    </tr>
                    <tr>
                        <td>Legal Person Identifier</td>
                        <td>{kyb.legal_person_identifier}</td>
                    </tr>
                    <tr>
                        <td>Jurisdiction Code</td>
                        <td>{kyb.jurisdiction_code}</td>
                    </tr>
                    <tr>
                        <td>Business Role</td>
                        <td>{kyb.business_role}</td>
                    </tr>
                    <tr>
                        <td>Address</td>
                        <td>{kyb.address}</td>
                    </tr>
                    <tr>
                        <td>LEI</td>
                        <td>{kyb.lei}</td>
                    </tr>
                    <tr>
                        <td>Vat Registration</td>
                        <td>{kyb.vat_registration}</td>
                    </tr>
                    <tr>
                        <td>Birthdate</td>
                        <td>{kyb.birthdate}</td>
                    </tr>
                    <tr>
                        <td>Trading Status</td>
                        <td>{kyb.trading_status}</td>
                    </tr>
                    <tr>
                        <td>Given Name</td>
                        <td>{kyb.given_name}</td>
                    </tr>
                    <tr>
                        <td>Family Name</td>
                        <td>{kyb.family_name}</td>
                    </tr>
                    <tr>
                        <td>Sub Jurisdiction</td>
                        <td>{kyb.sub_jurisdiction}</td>
                    </tr>
                    </tbody>

                </table>
                }


            </main>
        </Layout>
    );
}